### ISSUE TITLE
IndestructibleGrindOwner not working

### ISSUE THREAD

**Issue by MrPurple6814** [JimLess/BeaconSecurity#1]
IndestructibleGrindOwner(on/off) - Turn on/off the ability to grind own property on indestructible grids. Default: on

From what I am reading this is supposed to let you grind your own stuff and I am finding that it does not matter if this is on or off I am not able to grind down my grid unless I turn the protection beacon off first...

On my server I set it up so as long as you are 1 away from the beacon the protection turns on and then I was building on the far side of my base and misplaced something and tried to grind it down and found that I could not. so if I misplace something I have to run over to my beacon and then back again and grind the offending piece before the beacon activates again.

If you would like to test this for yourself just hop on my server 108.61.121.75:27025
It should be running 24/7 and is currently on 181.301

**Comment by JimLess** [comment]
This option works only for listed grids. Not issue...
